"""Shared imports for the dashboard page."""

from flashstudio.constants import (  # noqa: F401
    IMG_EXTENSIONS, DEFAULT_SAVE_DIR, MAX_DISPLAY_RUNS,
    CKPT_BEST, CKPT_BEST_INFERENCE, CKPT_FINAL_INFERENCE,
    CKPT_FINAL_FP16, TRAINING_LOG_CSV,
    COLOR_SUCCESS, COLOR_TEXT_PRIMARY, COLOR_TEXT_SECONDARY,
    COLOR_TEXT_MUTED, COLOR_BORDER, COLOR_BG_HIGHLIGHT,
    GPU_NAME_TRUNCATE, DATASET_NAME_TRUNCATE,
)
